# Generated by Django 5.1.2 on 2024-10-17 08:36

import common.validators.image_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics/', validators=[common.validators.image_validator.ImageValidator(max_height=800, max_size=5242880, max_width=1200)]),
        ),
    ]
