# Generated by Django 5.1.2 on 2024-10-14 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0002_alter_investorprofile_investor_logo'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('investor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investorprofile')),
                ('startup_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
            options={
                'verbose_name': 'Investment Tracking',
                'verbose_name_plural': 'Investment Tracking',
                'ordering': ['-saved_at'],
            },
        ),
    ]