# Generated by Django 5.1.2 on 2024-10-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment_tracking', '0002_rename_investor_id_investmenttracking_investor_and_more'),
        ('investors', '0002_alter_investorprofile_investor_logo'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='investmenttracking',
            constraint=models.UniqueConstraint(fields=('investor', 'startup'), name='unique_investor_startup'),
        ),
    ]
