apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres:17.0-alpine
        envFrom:
        - configMapRef:
            name: configmap
        - secretRef:
            name: django-secret
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data
      volumes:
        - name: data
          emptyDir: {}
