apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        command: ["celery", "-A", "forum.celery.app", "worker", "--loglevel=info"]
        envFrom:
        - configMapRef:
            name: worker-config
