# Generated by Django 5.1.2 on 2024-10-14 16:56

import common.validators.image_validator
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startupprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Startup Profile', 'verbose_name_plural': 'Startup Profiles'},
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='startup_logo',
            field=models.ImageField(blank=True, null=True, upload_to='startup_logos/', validators=[common.validators.image_validator.ImageValidator(max_height=800, max_size=5242880, max_width=1200)]),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL),
        ),
    ]
