apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: saberan/flower:latest
        command:
          - celery
          - -A
          - forum.celery
          - flower

        #command: ["celery", "-A", "forum.celery.app", "flower", "--loglevel=info"]
        envFrom:
          - configMapRef:
              name: forum-config
        livenessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5555
          initialDelaySeconds: 30
          periodSeconds: 10

