apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
      - name: flower
        image: docker-flower
        imagePullPolicy: IfNotPresent
        command: ["celery", "-A", "forum.celery.app", "flower"]
        ports:
        - containerPort: 5555
        envFrom:
        - configMapRef:
            name: flower-config
