apiVersion: apps/v1
kind: Deployment
metadata:
  name: communications
spec:
  replicas: 2
  selector:
    matchLabels:
      app: communications
  template:
    metadata:
      labels:
        app: communications
    spec:
      containers:
      - name: communications
        image: docker/python/Dockerfile
        command: ["daphne", "-p", "8001", "-b", "0.0.0.0", "forum.asgi:application"]
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: communications-config
