# Generated by Django 5.1.2 on 2024-10-17 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investors', '0002_alter_investorprofile_investor_logo'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(choices=[(1, 'Follow'), (2, 'Message'), (3, 'Update')])),
                ('status', models.IntegerField(choices=[(0, 'Unread'), (1, 'Read')], default=0)),
                ('message_id', models.CharField(blank=True, max_length=24, null=True)),
                ('delivery_status', models.IntegerField(blank=True, choices=[(0, 'Failed'), (1, 'Sent')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investors.investorprofile')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile')),
            ],
        ),
    ]
