# Generated by Django 5.1.2 on 2024-11-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message_id',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
