# Generated by Django 5.1.2 on 2024-11-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreferences_rolesnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
