# Generated by Django 5.1.2 on 2024-11-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_project'),
        ('notifications', '0002_notificationpreferences_rolesnotifications'),
    ]

    operations = [
    ]
