# Generated by Django 5.1.3 on 2024-11-06 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_message_id'),
        ('notifications', '0002_notificationpreferences_rolesnotifications'),
    ]

    operations = [
    ]
