# Generated by Django 5.1.3 on 2024-11-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_merge_20241106_1754'),
        ('notifications', '0003_merge_20241106_2144'),
    ]

    operations = [
    ]
