# Generated by Django 5.1.3 on 2024-11-09 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investors', '0002_alter_investorprofile_investor_logo'),
        ('notifications', '0004_merge_20241107_1941'),
        ('startups', '0002_alter_startupprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investors.investorprofile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='startup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='startups.startupprofile'),
        ),
    ]
